
[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 14, y = 10 }

[font]
normal = { family = "MesloLGS NF" }
offset = { y = 2 }
size = 12

[mouse]
hide_when_typing = true

[general]

live_config_reload = true
import = [
	"~/.config/alacritty/catppuccin-macchiato.toml"
]
