/**
 * Generate an aerospace config file based on declared workspaces.
 *
 * This speeds up the process of adding new workspaces which share the same keyboard shortcuts.
 *
 * Usage:
 * `deno run aerospace-config.ts > aerospace.toml`
 */

import { reload_aerospace } from "./app.ts";
import { AerospaceConfigBuilder } from "./config-builder.ts";

const config = AerospaceConfigBuilder.with_workspaces([
  "H", // Home
  "D", // Dev
  "P", // Production
  "S", // Second monitor
  "M", // Media
  "A", // AH
  1,
]);

config.mouse_follows_focus();
config.default_root_layout("accordion");
config.gaps({
  inner: 4,
  outer: 6,
  accordion: 30,
});

config.assign_to_built_in_monitor("S");
config.set_default_workspace("H");

const config_text = config.render();
const here = import.meta.dirname ?? Deno.cwd();
const with_header = `# This file was generated by ${here}/build.ts
# Do not edit this file directly, edit the source file instead
${config_text}`;

Deno.writeTextFileSync(`${here}/aerospace.toml`, with_header);

const header = "Generated the following config:";
const spacer = "-".repeat(header.length);

console.log(`
${header}
${spacer}

${config_text}
${spacer}
`);

console.log("Reloading aerospace...");
await reload_aerospace();
console.log("Done!");
