# Base starship configuration
# Additional settings are provided via Nix configuration

format = """$username$hostname[:](bright-black)$directory$line_break$character"""

right_format = "$cmd_duration"

[directory]
format = "[$path]($style)"
style = "bold bright-blue"
repo_root_style = "bold bright-blue"
before_repo_root_style = "white"
truncation_length = 2
truncation_symbol = "…/"
truncate_to_repo = false

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[✗](bold red)"

[username]
format = "[$user@]($style)"
style_user = "white"

[hostname]
format = "[$hostname]($style)"
style = "white"
ssh_only = false

[cmd_duration]
format = "[$duration](black)"