#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[palette]
  os = '#ACB0BE'
  blue = '#8AADF4'
  lavender = '#B7BDF8'
  pink = '#F5BDE6'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = 'p:os'
    template = '{{.Icon}} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:lavender'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ .Behind }}{{ end }}{{ if gt .Ahead 0 }}⇡{{ .Ahead }}{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = "\ue725 " 
      commit_icon = "\uf417 "
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:os'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:pink{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}p:pink{{end}}']
  template = '❯ '

[secondary_prompt]
  foreground = 'p:pink'
  template = '❯❯ '
